site:
  title: Boost.Unordered
  start_page: unordered::index.adoc
content:
  sources:
  - url: ..
    start_path: doc
    branches: HEAD
output:
  dir: html
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  output_dir: unordered/_
